### ISSUE TITLE
`Type`/`Xtype` instances for SVG and HTML are not the same.

### ISSUE THREAD

**Issue by alaendle** [mikesol/purescript-deku#100]
Maybe I've missed something, but could it be that the `Type` instances only cover SVG and not HTML tags?
https://github.com/mikesol/purescript-deku/blob/c5c90450885592aca78c5e18ab91f9ab4603c959/src/Deku/DOM/Attr/Type.purs#L14

However `Xtype` has all instance - so maybe just a matter of inconsistency?
https://github.com/mikesol/purescript-deku/blob/c5c90450885592aca78c5e18ab91f9ab4603c959/src/Deku/DOM/Attr/Xtype.purs#L23

HTML type attributes:
https://www.w3schools.com/tags/att_type.asp

SVG type attributes:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/type

**Comment by mikesol** [comment]
Thanks for reporting this! It's been fixed in current `main`, where a namespace distinction is made between the DOM and SVG.
