### ISSUE TITLE
Deku.Lifecycle is removed? where it is right now?

### ISSUE THREAD

**Issue by srghma** [mikesol/purescript-deku#118]
https://github.com/mikesol/purescript-deku/blob/1510c177cc3d7f0f28be8c799a4e087b1303da7e/README.md?plain=1#L87

removed?

how to do `onWillMount`?

**Comment by mikesol** [comment]
There is no replacement, but the idea is to push this to the effect boundary - for example at the level of the listener that causes an element to appear.
