### ISSUE TITLE
autofocus doesn't focus

### ISSUE THREAD

**Issue by Ebmtranceboy** [mikesol/purescript-deku#24]
I'm trying to produce 
 `<input autofocus>` (HTML)
In Javascript, I would do
```let body = document.querySelector("body");
let inp = document.createElement("input");
inp.setAttribute("autofocus","");
body.appendChild(inp);
```
With Deku, I tried  `main = runInBody ( D.input (bang $ D.Autofocus := "") [] )` (PureScript) but, event if the browser inspector shows the correct HTML, the input element is not focused.

**Comment by Ebmtranceboy** [comment]
I initially thought the misbehavior had to do with boolean attributes but `disabled` works as expected for instance.

**Comment by mikesol** [comment]
Thanks for the detailed write-up!

The bug arises from the fact that `autofocus` has to be set _before_ an element is added to the body (as you do in your JS example) whereas Deku currently sets attributes after appending. I can fix this & roll a new release tomorrow.

**Comment by mikesol** [comment]
I just rolled a [new release](https://github.com/mikesol/purescript-deku/releases/tag/v0.4.5) with a fix & I've added a small test in the `hello-world` example to verify that it works. Please let me know if there are any issues & thanks for reporting this!

**Comment by Ebmtranceboy** [comment]
All is OK for me. Thanks!
