### ISSUE TITLE
`pursx` can not parse some attribute content

### ISSUE THREAD

**Issue by MuratOzsoyler** [mikesol/purescript-deku#87]
For more info please refer to [this README](https://github.com/MuratOzsoyler/try-pursx-attrs/blob/master/README.md).

You find simplified repo at [here](https://github.com/MuratOzsoyler/try-pursx-attrs.git).

This issue is only an inconvenience and can be low level.

**Comment by mikesol** [comment]
Thanks for the report!
While `pursx` works for the original intended use case (copying and pasting tailwind css examples) it misses many important cases. Over the summer, I hope to do a `pursx` revamp and improve its stability!

**Comment by jquesada2016** [comment]
Has there been any progress on this?

**Comment by mikesol** [comment]
Hi!

Apologies, no not yet, I've been too busy at work, but my goal over Christmas break is to polish off a whole bunch of deku things including this!

Mike Solomon
C.E.O. @Meeshkan
https://www.meeshkan.com

Sent via Superhuman ( ***@***.*** )

**Comment by Ebmtranceboy** [comment]
I've noticed something about spelling : https://try.purescript.org/?gist=cc818cbcfa989fd585ec8cdb74b0cbd4
Even if my browser inspector confirms "animateTransform" is well-undestood, I can't change `animatetransform` to `animateTransform` in the gist above without introducing a type error.

**Comment by mikesol** [comment]
Thanks for reporting this!

I've been battling a nasty case of the flu all week but I hope to check a few deku issues next week!

~Mike

---
Mike Solomon
C.E.O. @Meeshkan
https://www.meeshkan.com

Sent via Superhuman ( ***@***.*** )

**Comment by Ebmtranceboy** [comment]
Sorry to hear. Hope you feeling better. 
I've dug a little, mostly for SVG. Here are my [observations](https://gist.github.com/Ebmtranceboy/aea6d29f384474b63dbd836ce202a025): 
* `animateMotion` suffers the same spelling trouble as `animateTransform` 
* I can't compile an SVG attribute with `(~~)` when its second argument is not `{}` (I can with `(~!~)` though)

**Comment by mikesol** [comment]
Hi @MuratOzsoyler ! Just to give you a small update here, there's a PR https://github.com/mikesol/purescript-deku/pull/123 that fixes this. Once it's merged I'll close this issue 👍

**Comment by mikesol** [comment]
Merged!
