### ISSUE TITLE
How to deal with binary attributes?

### ISSUE THREAD

**Issue by toastal** [mikesol/purescript-deku#89]
With a property like `<input disabled>` what is the most ergonomic way to handle `disabled`? All of the examples show little `if _ then`s, but I'm curious about when you need to completely remove the attribute. I know you could concat lists, but surely there's an `Alt.do`-compatible option? Something with `guard`?? And what is on the value side, `D.Disable !:= null`?

**Comment by mikesol** [comment]
To unset an attribute, you can set it to `unit`. For more info, you can check out (**Unsetting an attribute with a hook**)[https://purescript-deku.netlify.app/core-concepts/state#unsetting-an-attribute-with-a-hook] in the Deku documentation.
